version: '3.8'
services:
  docusaurus:
    image: node:18.12-slim
    ports:
      - 8180:3000
    volumes:
      - ./:/home/app
    working_dir: /home/app
    command: >
      sh -c "npm install && npm start"
